### ISSUE TITLE
Add default icons in font format

### ISSUE THREAD

**Issue by MrTibbles** [jaakmusic/primitives#10]
Add font family of core icons to allow for simple changing of color.

**Comment by lukehedger** [comment]
We could do something like this (based on Google's [Material Icons](http://google.github.io/material-design-icons/#icon-font-for-the-web)):
```
const MaterialIcon = ({type}) => (
  <i className='material-icons'>
    { type }
  </i>
)

export const Icon = styled(MaterialIcon)`
  color: ${({color, theme}) => theme.palette[color] || color};
`
```

And used like so:
```
<Icon type='menu' />
```

But maybe `<Icon>` is better implemented at application-level, rather than in the library?
