### ISSUE TITLE
Generic signature for attributes using theme props

### ISSUE THREAD

**Issue by lukehedger** [jaakmusic/primitives#24]
Implement a generic signature for attributes that make use of theme props:

```
color: ${({ color, theme }) => theme.palette[color] || color};
fontSize: ${({ fontSize, theme }) => theme.typography[fontSize] || fontSize};
```

This way, the prop value can either be a theme sub-key or a valid CSS value:

```
<Component color='primary' fontSize='baseFontSize' />
<Component color='coral' fontSize='16px' />
```

**Comment by lukehedger** [comment]
Could even have utility methods for common theme props:
```
const getColor = ({ color, theme }) => theme.palette[color] || color

// color: getColor(props)
```

**Comment by MrTibbles** [comment]
Sounds sensible yeah. Almost an extension of polished, in terms of the short hand method nature of it. 👍

**Comment by lukehedger** [comment]
Yeah, exactly!
