### ISSUE TITLE
🆕 Add h1 primitive

### ISSUE THREAD

**Issue by MrTibbles** [jaakmusic/primitives#43]
## Description
Add `<H1 />` primitive for SEO and semantic mark-up interests.

## What would you name this primitive?
`<H1 />`
`<Title tag='1' />` => `<h1 />`, `<Title tag='2' />` => `<h2 />`

Two proposed implementation methods. `h1` is the most desired element for SEO interests, whereas the more flexible `<Title />` primitive would be for semantic mark-up. I would propose the functional approach of `<H1 />` is chosen, with the option to add the latter option further down the line, based on _user demand_.

## What are its use cases?
Main header for a site to aid SEO. 

## Example implementation
`<H1 color='lemonchiffon' />`

**Comment by lukehedger** [comment]
Totally agree, this is definitely needed.

I quite like the idea of a combined primitive, maybe called [Heading](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements)?

```
<Heading /> => h1
<Heading level='1' /> => h1
...
<Heading level='6' /> => h6
```

**Comment by MrTibbles** [comment]
Reassuringly in harmony.
I deliberately didnt use head based naming as it could be confused with `<header />` and the `<head />` of documents. I do realise that it stands for that in `h1...h6` terms, so can see your reason. Do you get my thought process? 🤔

**Comment by MrTibbles** [comment]
However, if MDN document that way. happy to follow their _head_ on this one.

**Comment by lukehedger** [comment]
Yeah, I had thought about possible confusion there too but reckon we should follow HTML semantics (and MDN 🙏 )

**Comment by lukehedger** [comment]
This looks to be the best way to do this: https://codesandbox.io/s/n5nRmZBv4
